package id.innovarebornbensin.tagihanlistrik;
import javax.swing.*;
import com.formdev.flatlaf.themes.*;

public class TagihanListrik extends javax.swing.JFrame {
    
    public TagihanListrik() {
        initComponents();
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGolongan = new javax.swing.ButtonGroup();
        lbHeading = new javax.swing.JLabel();
        lbPemakaian = new javax.swing.JLabel();
        rbGol1 = new javax.swing.JRadioButton();
        rbGol2 = new javax.swing.JRadioButton();
        rbGol3 = new javax.swing.JRadioButton();
        lbGolongan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpTarif = new javax.swing.JTextPane();
        tbHitung = new javax.swing.JButton();
        tbKeluar = new javax.swing.JButton();
        tfPemakaian = new javax.swing.JTextField();

        bgGolongan.add(rbGol1);
        bgGolongan.add(rbGol2);
        bgGolongan.add(rbGol3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hitung Tagihan Listrik");

        lbHeading.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        lbHeading.setText("Penghitung Tagihan Listrik");

        lbPemakaian.setText("Pemakaian (kWh)");

        rbGol1.setText("R1");
        rbGol1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rbGol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGol1ActionPerformed(evt);
            }
        });

        rbGol2.setText("R2");
        rbGol2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGol2ActionPerformed(evt);
            }
        });

        rbGol3.setText("R3");
        rbGol3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGol3ActionPerformed(evt);
            }
        });

        lbGolongan.setText("Golongan");

        tpTarif.setEditable(false);
        jScrollPane1.setViewportView(tpTarif);

        tbHitung.setText("Hitung!");
        tbHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHitungActionPerformed(evt);
            }
        });

        tbKeluar.setText("Keluar");
        tbKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHeading)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPemakaian)
                                    .addComponent(tfPemakaian, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbGol1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbGol2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbGol3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(tbKeluar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbHitung)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(lbHeading)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPemakaian)
                    .addComponent(lbGolongan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbGol1)
                    .addComponent(rbGol2)
                    .addComponent(rbGol3)
                    .addComponent(tfPemakaian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbHitung)
                    .addComponent(tbKeluar))
                .addGap(42, 42, 42))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbGol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGol1ActionPerformed
        // TODO add your handling code here:
        tpTarif.setText("Golongan anda: R1 \nDaya: 1300 VA \nTarif Listrik: Rp800/kWh");
    }//GEN-LAST:event_rbGol1ActionPerformed

    private void rbGol2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGol2ActionPerformed
        // TODO add your handling code here:
        tpTarif.setText("Golongan anda: R2 \nDaya: 2200 VA \nTarif Listrik: Rp1300/kWh");
    }//GEN-LAST:event_rbGol2ActionPerformed

    private void rbGol3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGol3ActionPerformed
        // TODO add your handling code here:
        tpTarif.setText("Golongan anda: R3 \nDaya: 3500 VA\nTarif Listrik: Rp1500/kWh");
    }//GEN-LAST:event_rbGol3ActionPerformed

    private void tbKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_tbKeluarActionPerformed

    private void tbHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHitungActionPerformed
        // TODO add your handling code here:
        try {
            double pemakaian = Double.parseDouble(tfPemakaian.getText());
            double totalR1 = pemakaian * 800;
            double totalR2 = pemakaian * 1300;
            double totalR3 = pemakaian * 1500;
            
            if (rbGol1.isSelected()) {
                JOptionPane.showMessageDialog(this, "Golongan anda: R1 (1300 VA)\nPemakaian anda: " + pemakaian + " kWh" +
                "\nTarif Listrik: Rp800/kWh \nTagihan yang harus dibayar: Rp" + totalR1, 
                "Info Tagihan Listrik",
                JOptionPane.INFORMATION_MESSAGE);
            }
            
            else if (rbGol2.isSelected()) {
                JOptionPane.showMessageDialog(this, "Golongan anda: R2 (2200 VA)\nPemakaian anda: " + pemakaian + " kWh" +
                "\nTarif Listrik: Rp1300/kWh \nTagihan yang harus dibayar: Rp" + totalR2, 
                "Info Tagihan Listrik",
                JOptionPane.INFORMATION_MESSAGE);
            }
            
            else if (rbGol3.isSelected()) {
                JOptionPane.showMessageDialog(this, "Golongan anda: R3 (3500 VA)\nPemakaian anda: " + pemakaian + " kWh" +
                "\nTarif Listrik: Rp1500/kWh \nTagihan yang harus dibayar: Rp" + totalR3, 
                "Info Tagihan Listrik",
                JOptionPane.INFORMATION_MESSAGE);
            }
            
            else {
                JOptionPane.showMessageDialog(this, "Golongan tidak sah.", "Galat", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input data kosong atau tidak sah. \nAlasan: " + e.getMessage(), "Galat", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tbHitungActionPerformed

    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        FlatMacLightLaf.setup();
        //</editor-fold>
        
        java.awt.EventQueue.invokeLater(() -> {
            new TagihanListrik().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGolongan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbGolongan;
    private javax.swing.JLabel lbHeading;
    private javax.swing.JLabel lbPemakaian;
    private javax.swing.JRadioButton rbGol1;
    private javax.swing.JRadioButton rbGol2;
    private javax.swing.JRadioButton rbGol3;
    private javax.swing.JButton tbHitung;
    private javax.swing.JButton tbKeluar;
    private javax.swing.JTextField tfPemakaian;
    private javax.swing.JTextPane tpTarif;
    // End of variables declaration//GEN-END:variables
}
